##Path constant
IMAGES = "./data"
GROUND_TRUTH = "ground_truth/"
PROCESS_GROUND_TRUTH = GROUND_TRUTH +"process/"

TRAIN = IMAGES + "/train_75"
TRAIN_GROUND_TRUTH = IMAGES + "/train_75_ground_truth"
TRAIN_PROCESS_GROUND_TRUTH = TRAIN_GROUND_TRUTH + "/process"

VALIDATION = IMAGES + "/validation_10"
VALIDATION_GROUND_TRUTH = IMAGES + "/validation_10_ground_truth"
VALIDATION_PROCESS_GROUND_TRUTH = VALIDATION_GROUND_TRUTH +"/process"

TEST = IMAGES + "/test_15"
TEST_GROUND_TRUTH = IMAGES + "/test_15_ground_truth"
TEST_PROCESS_GROUND_TRUTH = TEST_GROUND_TRUTH+"/process"


## INDEX CORRESPONDANCE
TEXT_AREA = (255,255,0) # Yellow
LARGE_CAPTIAL = 1 # light blue
FILLER = 2 #Green
SMALL_CAPITAL = 3 #MAGENTA
DECORATION = (255,0,0) #RED
TEXT_LINE = (0,0,255) #BLUE
BACKGROUND = 6 #Black

LAYOUTS = [DECORATION, TEXT_AREA, TEXT_LINE]


MAPPING_LABEL = {
    DECORATION: 1,
    TEXT_AREA: 2,
    TEXT_LINE: 3
}
